# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install
      
    - name: Build 
      run: yarn build
      
    - name: Instal gh-pages
      run:  yarn add gh-pages
            
    - name: Config email
      run: git config --global user.email "you@example.com"
     
    - name: Config name 
      run: git config --global user.name "Your Name"    

    - name: set-url
      run: git remote set-url origin https://gavelino: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@github.com/gavelino/ci_actions2  
         
    - name: Deploy App 
      run: yarn deploy

      